import Mathlib.Data.Nat.Log
import Mathlib.Data.Finset.Card
import Mathlib.Tactic

set_option maxHeartbeats 0
set_option relaxedAutoImplicit false
set_option autoImplicit false

/-!
# Halving Algorithm and Its Optimal Mistake Bound

## Main results

- `Halving.voteFor_false_add_true`: The false-voters and true-voters partition the current version space.
- `Halving.update_subset`: A version-space update is a subset of the old version space.
- `Halving.target_mem_update`: In the realizable setting, the target hypothesis survives every update.
- `Halving.mistake_halves`: Every mistake leaves at most half the hypotheses.
- `Halving.log_succ_le_log_of_double_le`: If `b` is positive and `2*b ≤ a`, then `log₂ b + 1 ≤ log₂ a`.
- `Halving.mistakes_bound`: In the realizable setting, the Halving Algorithm makes at most `log₂ |V|` mistakes.
- `Halving.halving_bound`: The mistake bound starting from the initial finite hypothesis class `H`.

## References

- Original formalization by Arhaan Aggarwal
-/

namespace Halving

variable {Hyp X : Type*}

/-- The hypotheses in `V` that vote for label `y` on input `x`. -/
def voteFor (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) (y : Bool) :
    Finset Hyp :=
  V.filter (fun h => eval h x = y)

/-- Halving prediction: predict 1/true on ties, matching the PDF. -/
def predict (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) : Bool :=
  if (voteFor eval V x true).card ≥ (voteFor eval V x false).card then
    true
  else
    false

/-- Version-space update after observing label `y` at input `x`. -/
def update (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) (y : Bool) :
    Finset Hyp :=
  voteFor eval V x y

/-- The false-voters and true-voters partition the current version space. -/
lemma voteFor_false_add_true
    (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) :
    (voteFor eval V x false).card + (voteFor eval V x true).card = V.card := by
  unfold voteFor
  have hfilter :
      V.filter (fun h : Hyp => eval h x = true) =
        V.filter (fun h : Hyp => ¬ eval h x = false) := by
    ext h
    cases eval h x <;> simp
  rw [hfilter]
  exact Finset.filter_card_add_filter_neg_card_eq_card
    (s := V) (p := fun h : Hyp => eval h x = false)

/-- A version-space update is a subset of the old version space. -/
lemma update_subset
    (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) (y : Bool) :
    update eval V x y ⊆ V := by
  intro h hh
  have hh' : h ∈ V ∧ eval h x = y := by
    simpa [update, voteFor] using hh
  exact hh'.1

/-- In the realizable setting, the target hypothesis survives every update. -/
lemma target_mem_update
    (eval : Hyp → X → Bool) (target : Hyp) (V : Finset Hyp) (x : X)
    (htarget : target ∈ V) :
    target ∈ update eval V x (eval target x) := by
  simp [update, voteFor, htarget]

/-- The key halving lemma: every mistake leaves at most half the hypotheses. -/
lemma mistake_halves
    (eval : Hyp → X → Bool) (V : Finset Hyp) (x : X) (y : Bool)
    (hmistake : predict eval V x ≠ y) :
    2 * (update eval V x y).card ≤ V.card := by
  cases y
  · -- true label is false/0, so a mistake means the algorithm predicted true/1.
    unfold predict at hmistake
    by_cases hmaj :
        (voteFor eval V x true).card ≥ (voteFor eval V x false).card
    · have hsum := voteFor_false_add_true (eval := eval) (V := V) (x := x)
      simp [update, hmaj] at hmistake ⊢
      omega
    · simp [hmaj] at hmistake
  · -- true label is true/1, so a mistake means the algorithm predicted false/0.
    unfold predict at hmistake
    by_cases hmaj :
        (voteFor eval V x true).card ≥ (voteFor eval V x false).card
    · simp [hmaj] at hmistake
    · have hsum := voteFor_false_add_true (eval := eval) (V := V) (x := x)
      have hle :
          (voteFor eval V x true).card ≤
            (voteFor eval V x false).card := by
        omega
      simp [update, hmaj] at hmistake ⊢
      omega

/-- Numeric log step: if `b` is positive and `2*b ≤ a`, then `log₂ b + 1 ≤ log₂ a`. -/
lemma log_succ_le_log_of_double_le {a b : ℕ}
    (hb : 0 < b) (hhalve : 2 * b ≤ a) :
    Nat.log 2 b + 1 ≤ Nat.log 2 a := by
  have hbne : b ≠ 0 := by omega
  have hpowlog : 2 ^ Nat.log 2 b ≤ b :=
    Nat.pow_log_le_self 2 hbne
  have hpow : 2 ^ (Nat.log 2 b + 1) ≤ a := by
    calc
      2 ^ (Nat.log 2 b + 1)
          = 2 ^ Nat.log 2 b * 2 := by
              rw [pow_succ]
      _ ≤ b * 2 := Nat.mul_le_mul_right 2 hpowlog
      _ = 2 * b := by omega
      _ ≤ a := hhalve
  exact Nat.le_log_of_pow_le (by norm_num : 1 < 2) hpow

/-- Run the Halving Algorithm over a finite list of inputs, with labels generated by `target`. -/
def mistakes (eval : Hyp → X → Bool) (target : Hyp) (V : Finset Hyp) :
    List X → ℕ
  | [] => 0
  | x :: xs =>
      let y := eval target x
      let V' := update eval V x y
      (if predict eval V x = y then 0 else 1) + mistakes eval target V' xs

/-- Main theorem: in the realizable setting, the Halving Algorithm makes at most `log₂ |V|` mistakes. -/
theorem mistakes_bound
    (eval : Hyp → X → Bool) (target : Hyp) (V : Finset Hyp) (xs : List X)
    (htarget : target ∈ V) :
    mistakes eval target V xs ≤ Nat.log 2 V.card := by
  induction xs generalizing V with
  | nil =>
      simp [mistakes]
  | cons x xs ih =>
      let y := eval target x
      let V' := update eval V x y
      have htarget' : target ∈ V' := by
        simpa [V', y] using target_mem_update eval target V x htarget
      have ih' : mistakes eval target V' xs ≤ Nat.log 2 V'.card :=
        ih V' htarget'
      by_cases hcorr : predict eval V x = y
      · -- No mistake: the version space can only shrink.
        have hsubset : V' ⊆ V := by
          simpa [V', y] using update_subset eval V x y
        have hcard : V'.card ≤ V.card := Finset.card_le_card hsubset
        have hlog : Nat.log 2 V'.card ≤ Nat.log 2 V.card :=
          Nat.log_mono_right hcard
        calc
          mistakes eval target V (x :: xs)
              = mistakes eval target V' xs := by
                  simp [mistakes, y, V', hcorr]
          _ ≤ Nat.log 2 V'.card := ih'
          _ ≤ Nat.log 2 V.card := hlog
      · -- Mistake: apply the halving lemma and spend one unit of logarithmic budget.
        have hhalve : 2 * V'.card ≤ V.card := by
          simpa [V', y] using mistake_halves eval V x y hcorr
        have hpos : 0 < V'.card := by
          exact Finset.card_pos.mpr ⟨target, htarget'⟩
        have hlogstep : Nat.log 2 V'.card + 1 ≤ Nat.log 2 V.card :=
          log_succ_le_log_of_double_le hpos hhalve
        calc
          mistakes eval target V (x :: xs)
              = 1 + mistakes eval target V' xs := by
                  simp [mistakes, y, V', hcorr]
          _ ≤ 1 + Nat.log 2 V'.card := Nat.add_le_add_left ih' 1
          _ = Nat.log 2 V'.card + 1 := by omega
          _ ≤ Nat.log 2 V.card := hlogstep

/-- The version of the theorem starting from the initial finite hypothesis class `H`. -/
theorem halving_bound
    (eval : Hyp → X → Bool) (target : Hyp) (H : Finset Hyp) (xs : List X)
    (htarget : target ∈ H) :
    mistakes eval target H xs ≤ Nat.log 2 H.card :=
  mistakes_bound eval target H xs htarget

end Halving
