/-
Copyright (c) 2026 Karim Abdel Sadek and Mark Bedaywi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Karim Abdel Sadek, Mark Bedaywi
-/

import TCSlib.LearningTheory.Hedge

set_option maxHeartbeats 0
set_option relaxedAutoImplicit false
set_option autoImplicit false

open Real Finset BigOperators

/-!
# Adaptive Episodes for Hedge

## Main results

- `episodeLossSeq_valid`: The realized loss sequence of any generated learner/adversary episode is valid.
- `Episode.losses_valid`: The loss sequence stored by an `Episode` is valid.
- `hedge_regret_bound_tight_episode`: Hedge's tight regret bound stated over generated adaptive episodes.
- `hedge_regret_bound_tight_of_episode`: The tight regret bound for a packaged `Episode` whose learner is Hedge.

## References

- Original formalization by Karim Abdel Sadek, Mark Bedaywi
-/

/-! ## Histories, Policies, and Adversaries -/

/-- A length-`t` history of loss vectors for `N` experts. -/
-- A history records only past losses.  At time `t`, its domain is `Fin t`, so
-- there is no entry for the current or future rounds.
def LossHistory (N : ℕ) (t : ℕ) := Fin t → Fin N → ℝ

namespace LossHistory

/-- Regard a history as the corresponding finite loss sequence. -/
-- This coercion-style helper lets us reuse the definitions from `Hedge.lean`,
-- which are stated for finite loss sequences.
def toLossSeq {N t : ℕ} (history : LossHistory N t) : LossSeq N t :=
  history

end LossHistory

/-- A learner policy maps every past loss history to a mixed strategy over experts. -/
-- The policy is deterministic here: once the past loss table is fixed, it
-- returns the distribution used for the next round.
structure LearnerPolicy (N : ℕ) [NeZero N] where
  /-- The distribution chosen after seeing a history of length `t`. -/
  weights : (t : ℕ) → LossHistory N t → Fin N → ℝ
  /-- Each coordinate of the chosen distribution is nonnegative. -/
  nonneg : ∀ t history i, 0 ≤ weights t history i
  /-- The distribution has total mass one. -/
  sum_one : ∀ t history, ∑ i : Fin N, weights t history i = 1

/-- An adaptive adversary maps the past loss history and current learner
distribution to the next loss vector.  The range condition keeps losses in
`[0, 1]`.
-/
-- This is adaptive but nonanticipating.  The adversary sees the past and the
-- current mixed strategy, then chooses the whole loss vector for this round.
-- It does not see a sampled expert action.
structure AdaptiveAdversary (N : ℕ) where
  /-- The loss vector selected at time `t` after observing history and distribution. -/
  loss : (t : ℕ) → LossHistory N t → (Fin N → ℝ) → Fin N → ℝ
  /-- Every selected loss coordinate is bounded between zero and one. -/
  valid : ∀ t history p i, 0 ≤ loss t history p i ∧ loss t history p i ≤ 1

/-! ## Hedge as a Learner Policy -/

/-- Hedge as a history-dependent learner policy. -/
-- The policy recomputes the Hedge distribution from the realized past losses.
-- This is the same `hedgeDist` from the pathwise theorem.
noncomputable def hedgePolicy (N : ℕ) [NeZero N] (η : ℝ) : LearnerPolicy N where
  weights t history i := hedgeDist η history.toLossSeq t i
  nonneg t history i := hedgeDist_nonneg η history.toLossSeq t i
  sum_one t history := hedgeDist_sum η history.toLossSeq t

/-! ## Generated Episodes -/

/-- The loss vector produced at natural time `t` by running a learner policy
against an adaptive adversary. -/
-- This is the online recursion.  To compute the loss vector at time `t`, we
-- first expose to the adversary the already generated prefix of length `t`,
-- then pass the learner's distribution for that same prefix.
def episodeLossNat {N : ℕ} [NeZero N]
    (learner : LearnerPolicy N) (adversary : AdaptiveAdversary N) :
    (t : ℕ) → Fin N → ℝ
  | t =>
      -- The recursive call is only used on `s : Fin t`, so the adversary at
      -- time `t` sees exactly the already-generated prefix of length `t`.
      adversary.loss t
        (fun s : Fin t => episodeLossNat learner adversary s.val)
        (learner.weights t (fun s : Fin t => episodeLossNat learner adversary s.val))
termination_by t => t
decreasing_by
  all_goals simp

/-- The finite loss sequence realized over `T` rounds by a learner/adversary pair. -/
-- The pathwise Hedge theorem expects a `LossSeq N T`, so we restrict the
-- natural-time recursion to the first `T` rounds.
def episodeLossSeq {N : ℕ} [NeZero N] (T : ℕ)
    (learner : LearnerPolicy N) (adversary : AdaptiveAdversary N) : LossSeq N T :=
  fun t i => episodeLossNat learner adversary t.val i

/-- A finite episode packages the realized loss sequence for a learner/adversary
interaction.  The consistency condition says that the stored loss sequence is
the one generated by the online recursion above. -/
-- The structure is useful when we want to talk about an episode as data:
-- learner, adversary, and realized losses all packaged together.
structure Episode (N T : ℕ) [NeZero N] where
  learner : LearnerPolicy N
  adversary : AdaptiveAdversary N
  losses : LossSeq N T
  losses_eq_generated :
    losses = episodeLossSeq T learner adversary

/-- The generated episode for a learner/adversary pair. -/
-- This is the canonical episode obtained by running the recursion.
def Episode.generated {N T : ℕ} [NeZero N]
    (learner : LearnerPolicy N) (adversary : AdaptiveAdversary N) : Episode N T where
  learner := learner
  adversary := adversary
  losses := episodeLossSeq T learner adversary
  losses_eq_generated := rfl

/-- The realized loss sequence of any generated learner/adversary episode is valid. -/
-- Validity is inherited directly from the adversary's range condition.
theorem episodeLossSeq_valid {N T : ℕ} [NeZero N]
    (learner : LearnerPolicy N) (adversary : AdaptiveAdversary N) :
    (episodeLossSeq T learner adversary).Valid := by
  intro t i
  dsimp [episodeLossSeq]
  -- Unfold the online recursion at the requested round.  The goal becomes
  -- exactly the adversary's promised range condition.
  rw [episodeLossNat.eq_1]
  exact adversary.valid t.val
    (fun s : Fin t.val => episodeLossNat learner adversary s.val)
    (learner.weights t.val (fun s : Fin t.val => episodeLossNat learner adversary s.val))
    i

/-- The loss sequence stored by an `Episode` is valid. -/
-- First rewrite the stored sequence to the generated one, then use the previous
-- validity result.
theorem Episode.losses_valid {N T : ℕ} [NeZero N] (episode : Episode N T) :
    episode.losses.Valid := by
  rw [episode.losses_eq_generated]
  exact episodeLossSeq_valid episode.learner episode.adversary

/-! ## Hedge Regret Against Adaptive Adversaries -/

/-- Hedge's tight regret bound stated over generated adaptive episodes.  The
proof is just the pathwise Hedge theorem applied to the realized loss sequence.
-/
-- This is why the adaptive case is easy here: the theorem in `Hedge.lean`
-- already holds for every fixed valid loss sequence.  Once the interaction has
-- generated such a sequence, adaptivity no longer needs a separate argument.
theorem hedge_regret_bound_tight_episode {N T : ℕ} [NeZero N] (η : ℝ)
    (hη_pos : 0 < η) (adversary : AdaptiveAdversary N) :
    regret η (episodeLossSeq T (hedgePolicy N η) adversary)
      ≤ Real.log N / η + η * T / 8 := by
  -- The reduction is deliberately small: generated episodes are valid loss
  -- sequences, and `hedge_regret_bound_tight` already handles every such
  -- sequence pathwise.
  exact hedge_regret_bound_tight η hη_pos
    (episodeLossSeq T (hedgePolicy N η) adversary)
    (episodeLossSeq_valid (hedgePolicy N η) adversary)

/-- The same bound for an `Episode` whose learner is Hedge. -/
-- This version is for packaged episodes.  The extra assumption says that the
-- learner field really is the Hedge policy with learning rate `η`.
theorem hedge_regret_bound_tight_of_episode {N T : ℕ} [NeZero N] (η : ℝ)
    (hη_pos : 0 < η) (episode : Episode N T)
    (hlearner : episode.learner = hedgePolicy N η) :
    regret η episode.losses ≤ Real.log N / η + η * T / 8 := by
  rw [episode.losses_eq_generated, hlearner]
  exact hedge_regret_bound_tight_episode η hη_pos episode.adversary
