/-
Copyright (c) 2026 Lucy Horowitz, Timothe Kasriel, and Mihir Singhal. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lucy Horowitz, Timothe Kasriel, Mihir Singhal
-/

import TCSlib.CommunicationComplexity.NewmanTheorem.FuncDisjointnessLowerBound.CoordinateVectorModel
import TCSlib.CommunicationComplexity.NewmanTheorem.Minimax

set_option maxHeartbeats 0
set_option relaxedAutoImplicit false
set_option autoImplicit false

/-!
# Disjointness lower bound: duality is measure preserving

The Alice/Bob duality of the hard sample space (`dualHardSample`) and of protocols
(`dualProtocol`) is shown to preserve the uniform hard distribution and its
disjoint-conditioned version, and to transport the transcript and the conditioning variable
`Z = (M, T, X_<T, Y_>T)` to their recoded duals. This is the formal content of the
'WLOG' step leading to eq. (6.2) in the proof of [RY20, Thm 6.13]: every Alice-side estimate
proved later can be applied to the dual protocol on dual samples to obtain the Bob-side
estimate. The file also introduces the transcript random variable `message`, bounds its
entropy by the communication in bits, and identifies the distributional error of a
protocol under the hard input distribution with the mass of an explicit event on the
sample space.

## Main definitions

* `message`: the transcript of a deterministic protocol on the input generated by a sample.
* `dualRawZValue`, `dualZValue`: the recoding of (raw, resp. achievable) `Z` values induced
  by protocol and sample duality.
* `protocolErrorEvent`: the set of samples on which a protocol errs on disjointness.

## Main results

* `volume_measurePreserving_dualHardSample`,
  `disjointCondMeasure_measurePreserving_dualHardSample`: sample duality preserves the
  uniform and the disjoint-conditioned hard distributions.
* `volume_cond_specialZeroZero_measureReal_le_two_mul_disjointSpecialYFalseMeasure`:
  conditioning on `(X_T, Y_T) = (0, 0)` costs at most a factor `2` over conditioning on
  `Y_T = 0` alone.
* `entropy_message_le_complexity_mul_log_two_of_measure`: the transcript entropy is at most
  `ℓ · log 2` for an `ℓ`-bit protocol.
* `zVariable_dualProtocol_dualHardSample`, `volume_zVariable_dualProtocol_dualZValue`: the
  `Z` variable of the dual protocol on a dual sample is the recoded `Z` value, and
  corresponding fibres have equal mass.
* `distributionalError_inputDist_eq_protocolErrorEvent`: the distributional error under the
  hard input distribution is the mass of `protocolErrorEvent`.

## References

* [RY20] A. Rao, A. Yehudayoff, *Communication Complexity and Applications*,
  Cambridge University Press, 2020.
* [Raz92] A. A. Razborov, "On the distributional complexity of disjointness",
  *Theoretical Computer Science* 106(2):385–390, 1992.
* [KS92] B. Kalyanasundaram, G. Schnitger, "The probabilistic communication complexity of
  set intersection", *SIAM J. Discrete Math.* 5(4):545–557, 1992.
* [BJKS04] Z. Bar-Yossef, T. S. Jayram, R. Kumar, D. Sivakumar, "An information statistics
  approach to data stream and communication complexity", *J. Comput. Syst. Sci.*
  68(4):702–732, 2004.

Original formalization by Lucy Horowitz, Timothe Kasriel, and Mihir Singhal.
-/

namespace CommunicationComplexity

open MeasureTheory ProbabilityTheory
open scoped BigOperators

namespace Functions.Disjointness

namespace RandomizedLowerBound

variable (n : ℕ+)

/-- A measure-preserving self-map leaves every random variable identically distributed with its
pullback along that map. -/
theorem identDistrib_self_comp_measurePreserving
    {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    {μ : Measure Ω} {T : Ω → Ω} (hT : MeasurePreserving T μ μ)
    (F : Ω → α) (hF : Measurable F) :
    IdentDistrib F (F ∘ T) μ μ := by
  refine ⟨hF.aemeasurable, (hF.comp hT.measurable).aemeasurable, ?_⟩
  nth_rw 1 [← hT.map_eq]
  rw [Measure.map_map hF hT.measurable]

/-- The preimage of a singleton under hard-sample duality is the dual singleton. -/
theorem dualHardSample_preimage_singleton (ω : HardSample n) :
    (dualHardSample n) ⁻¹' ({ω} : Set (HardSample n)) =
      {dualHardSample n ω} := by
  ext ω'
  constructor
  · intro h
    have h' : dualHardSample n ω' = ω := by
      simpa using h
    have h'' := congrArg (dualHardSample n) h'
    simpa [dualHardSample_dualHardSample] using h''
  · intro h
    have h' : ω' = dualHardSample n ω := by
      simpa using h
    rw [h']
    simp [dualHardSample_dualHardSample]

/-- The uniform hard-sample measure gives the same mass to a sample and its dual. -/
theorem volume_measureReal_singleton_dualHardSample (ω : HardSample n) :
    volume.real ({dualHardSample n ω} : Set (HardSample n)) =
      volume.real ({ω} : Set (HardSample n)) := by
  change ((ProbabilityTheory.uniformOn Set.univ : Measure (HardSample n)).real
      ({dualHardSample n ω} : Set (HardSample n))) =
    ((ProbabilityTheory.uniformOn Set.univ : Measure (HardSample n)).real
      ({ω} : Set (HardSample n)))
  repeat rw [Measure.real]
  rw [uniformOn_univ_measureReal_eq_card_subtype,
    uniformOn_univ_measureReal_eq_card_subtype]
  simp

/-- Hard-sample duality preserves the uniform hard-sample measure: the pushforward of the
uniform law on `HardSample n` along `dualHardSample` is the uniform law again. This is the
symmetry of the hard distribution under swapping Alice and Bob that justifies the 'WLOG'
step leading to eq. (6.2) in the proof of [RY20, Thm 6.13]. -/
theorem volume_measurePreserving_dualHardSample :
    MeasurePreserving (dualHardSample n)
      volume volume := by
  refine ⟨Measurable.of_discrete, ?_⟩
  rw [MeasureTheory.ext_iff_measureReal_singleton]
  intro ω
  rw [Measure.real]
  rw [Measure.map_apply Measurable.of_discrete MeasurableSet.of_discrete]
  rw [← Measure.real, dualHardSample_preimage_singleton,
    volume_measureReal_singleton_dualHardSample]

/-- The disjoint-conditioned hard-sample measure gives the same mass to a sample and its dual.

**Proof sketch.** Unfold the conditional measure as `P(𝒟 ∩ ·) / P(𝒟)`. Since a sample is
disjoint if and only if its dual is, split on whether the sample lies in the disjoint event:
if it does, both intersections are the corresponding singletons and the uniform law gives
them equal mass; if it does not, both intersections are empty and both sides vanish. -/
theorem disjointCondMeasure_measureReal_singleton_dualHardSample (ω : HardSample n) :
    (disjointCondMeasure n).real ({dualHardSample n ω} : Set (HardSample n)) =
      (disjointCondMeasure n).real ({ω} : Set (HardSample n)) := by
  rw [disjointCondMeasure]
  rw [ProbabilityTheory.cond_real_apply MeasurableSet.of_discrete]
  rw [ProbabilityTheory.cond_real_apply MeasurableSet.of_discrete]
  -- Step 1: a sample is disjoint iff its dual is; split on membership in the disjoint event.
  by_cases hω : ω ∈ disjointEvent n
  -- Step 2 (disjoint case): both intersections are singletons of equal uniform mass.
  · have hdual : dualHardSample n ω ∈ disjointEvent n :=
      (disjointEvent_dualHardSample n ω).2 hω
    have hleft :
        disjointEvent n ∩ ({dualHardSample n ω} : Set (HardSample n)) =
          {dualHardSample n ω} := by
      ext η
      simp [hdual]
    have hright : disjointEvent n ∩ ({ω} : Set (HardSample n)) = {ω} := by
      ext η
      simp [hω]
    rw [hleft, hright, volume_measureReal_singleton_dualHardSample]
  -- Step 3 (non-disjoint case): both intersections are empty, so both sides are `0`.
  · have hdual : dualHardSample n ω ∉ disjointEvent n := by
      intro h
      exact hω ((disjointEvent_dualHardSample n ω).1 h)
    have hleft :
        disjointEvent n ∩ ({dualHardSample n ω} : Set (HardSample n)) =
          ∅ := by
      ext η
      by_cases hη : η = dualHardSample n ω
      · subst η
        simp [hdual]
      · simp [hη]
    have hright : disjointEvent n ∩ ({ω} : Set (HardSample n)) = ∅ := by
      ext η
      by_cases hη : η = ω
      · subst η
        simp [hω]
      · simp [hη]
    rw [hleft, hright]

/-- Hard-sample duality preserves the disjoint-conditioned hard-sample measure: the pushforward
of `p(· | 𝒟)` along `dualHardSample` is `p(· | 𝒟)` again. This is the disjoint-conditioned
form of the Alice/Bob symmetry used in the 'WLOG' step leading to eq. (6.2) in the proof of
[RY20, Thm 6.13]. -/
theorem disjointCondMeasure_measurePreserving_dualHardSample :
    MeasurePreserving (dualHardSample n) (disjointCondMeasure n) (disjointCondMeasure n) := by
  refine ⟨Measurable.of_discrete, ?_⟩
  rw [MeasureTheory.ext_iff_measureReal_singleton]
  intro ω
  rw [Measure.real]
  rw [Measure.map_apply Measurable.of_discrete MeasurableSet.of_discrete]
  rw [← Measure.real, dualHardSample_preimage_singleton,
    disjointCondMeasure_measureReal_singleton_dualHardSample]

/-- Conditioning on a subevent of disjointness is the same under the ambient hard distribution and
under the hard distribution first conditioned on disjointness. -/
theorem volume_cond_eq_disjointCondMeasure_cond_of_subset_disjointEvent
    {A : Set (HardSample n)} (hA : A ⊆ disjointEvent n) :
    volume[|A] = (disjointCondMeasure n)[|A] := by
  rw [disjointCondMeasure]
  rw [ProbabilityTheory.cond_cond_eq_cond_inter
    MeasurableSet.of_discrete MeasurableSet.of_discrete volume]
  congr 1
  ext ω
  simp [hA]

/-- For every event `S` on the hard sample space, the probability of `S` conditioned on
`(X_T, Y_T) = (0, 0)` is at most twice its probability under the disjoint distribution
conditioned only on `Y_T = 0`. This is the reweighting step before Markov's inequality,
realising the factor `p(a_t = 0 | b_t = 0) = 1/2` in [RY20, Ch. 6, eq. (6.2)].

**Proof sketch.** Write `μ` for the disjoint-conditioned law and `Y0` for the event
`Y_T = 0`. Since `(X_T, Y_T) = (0, 0)` is a disjoint event, conditioning the ambient law on it
agrees with conditioning `μ` on it. Both sides are then quotients of the form
`μ(E ∩ S) / μ(E)`, with `μ((0,0)) = 1/3` and `μ(Y0) = 2/3`; since `(0,0) ⊆ Y0` the
numerator on the left is at most the numerator on the right, and `3 ≤ 2 · (3/2)` closes the
inequality. -/
theorem volume_cond_specialZeroZero_measureReal_le_two_mul_disjointSpecialYFalseMeasure
    (S : Set (HardSample n)) :
    (volume[|specialZeroZero n]).real S ≤
      2 * (disjointSpecialYFalseMeasure n).real S := by
  let μ : Measure (HardSample n) := disjointCondMeasure n
  let Y0 : Set (HardSample n) := (specialY n) ⁻¹' {false}
  -- Step 1: the event `(X_T, Y_T) = (0, 0)` is contained in `Y_T = 0`.
  have hzero_subset_y0 : specialZeroZero n ⊆ Y0 := by
    intro ω hω
    rw [specialZeroZero, specialBitsEvent] at hω
    simpa [Y0, specialY] using hω.2
  -- Step 2: conditioning the ambient law on a disjoint event equals conditioning `μ`.
  have hcond_zero :
      volume[|specialZeroZero n] = μ[|specialZeroZero n] := by
    simpa [μ] using
      volume_cond_eq_disjointCondMeasure_cond_of_subset_disjointEvent n
        (specialZeroZero_subset_disjointEvent n)
  -- Step 3: both sides are conditional quotients `μ(E ∩ S) / μ(E)`.
  have hleft :
      (volume[|specialZeroZero n]).real S =
        (μ.real (specialZeroZero n))⁻¹ * μ.real (specialZeroZero n ∩ S) := by
    rw [hcond_zero]
    rw [ProbabilityTheory.cond_real_apply MeasurableSet.of_discrete]
  have hright :
      (disjointSpecialYFalseMeasure n).real S =
        (μ.real Y0)⁻¹ * μ.real (Y0 ∩ S) := by
    rw [disjointSpecialYFalseMeasure]
    change (μ[|Y0]).real S = (μ.real Y0)⁻¹ * μ.real (Y0 ∩ S)
    rw [ProbabilityTheory.cond_real_apply MeasurableSet.of_discrete]
  -- Step 4: the denominators are `1/3` and `2/3`, and the numerators are monotone.
  have hzero_mass : μ.real (specialZeroZero n) = (1 / 3 : ℝ) := by
    simpa [μ] using disjointCondMeasure_measureReal_specialZeroZero n
  have hy0_mass : μ.real Y0 = (2 / 3 : ℝ) := by
    simpa [μ, Y0] using disjointCondMeasure_measureReal_specialY_false n
  have hmono : μ.real (specialZeroZero n ∩ S) ≤ μ.real (Y0 ∩ S) :=
    measureReal_mono (by
      intro ω hω
      exact ⟨hzero_subset_y0 hω.1, hω.2⟩)
  rw [hleft, hright, hzero_mass, hy0_mass]
  norm_num
  linarith

/-- The transcript random variable induced by a deterministic protocol on the hard sample
space: the transcript of `p` on the input pair generated by a sample. This is the message
variable `S` (also written `M`) of the proof of [RY20, Thm 6.13], see [RY20, Ch. 6,
eq. (6.3)]. -/
noncomputable def message
    (p : ProtocolType n)
    (ω : HardSample n) : TranscriptType n p :=
  p.transcript (input n ω)

open Classical in
/-- Under `D`, the transcript is a function of the generated disjoint coordinate vector. -/
theorem message_ae_eq_coordinateMessage
    (p : ProtocolType n) :
    message n p =ᵐ[disjointCondMeasure n]
      fun ω => coordinateMessage n p (disjointCoordinateVector n ω) := by
  filter_upwards [disjointCondMeasure_ae_disjointEvent n] with ω hω
  unfold message coordinateMessage input coordinateInput
  congr
  · ext j
    simp [X, coordinateXSet, coordinateXBit,
      disjointCoordinateVector_xBit_of_mem_disjointEvent n hω j]
  · ext j
    simp [Y, coordinateYSet, coordinateYBit,
      disjointCoordinateVector_yBit_of_mem_disjointEvent n hω j]

/-- The entropy of the transcript variable of an `ℓ`-bit protocol is at most `ℓ · log 2`,
under any measure on the hard sample space. This is the bound `H(S) ≤ ℓ` used in
[RY20, Ch. 6, eq. (6.3)], which rests on the protocol having at most `2^ℓ` transcripts
(cf. [RY20, Lemma 1.2]). Deviation: entropy is measured in nats, hence the factor `log 2`. -/
theorem entropy_message_le_complexity_mul_log_two_of_measure
    (p : ProtocolType n)
    (μ : Measure (HardSample n)) :
    H[message n p ; μ] ≤
      p.complexity * Real.log 2 := by
  letI : Nonempty (TranscriptType n p) := ⟨p.transcript (∅, ∅)⟩
  exact ProbabilityTheory.entropy_le_nat_mul_log_two_of_card_le_two_pow
    (message n p) μ
    (Deterministic.Protocol.card_transcript_le_two_pow_complexity p)

/-- The dual protocol transcript on the dual hard sample is the original transcript recoded
through protocol duality. -/
theorem message_dualProtocol_dualHardSample
    (p : ProtocolType n)
    (ω : HardSample n) :
    message n (dualProtocol n p) (dualHardSample n ω) =
      dualProtocolTranscriptMap n p (message n p ω) := by
  change (p.swap.comap (reverseSet n) (reverseSet n)).transcript
      (input n (dualHardSample n ω)) =
    dualProtocolTranscriptMap n p (p.transcript (input n ω))
  rw [input_dualHardSample, input]
  rw [← Deterministic.Protocol.transcriptComap_transcript p.swap (reverseSet n) (reverseSet n)
    (reverseSet n (Y n ω)) (reverseSet n (X n ω))]
  rw [reverseSet_reverseSet, reverseSet_reverseSet]
  rw [← Deterministic.Protocol.transcriptSwap_transcript p]
  rfl

/-- Dualize a raw `Z = (M,T,X_<T,Y_>T)` value by recoding the transcript and coarse
conditioning data. -/
def dualRawZValue
    (p : ProtocolType n)
    (z : RawZType n p) :
    RawZType n (dualProtocol n p) :=
  { transcript := dualProtocolTranscriptMap n p z.transcript
    specialCoordinate := Fin.rev z.specialCoordinate
    xBefore := reverseBoolVector n z.yAfter
    yAfter := reverseBoolVector n z.xBefore }

/-- The raw `Z = (M, T, X_<T, Y_>T)` record of the dual protocol on the dual of a sample is
the recoding `dualRawZValue` of the raw `Z` record of the original protocol on the original
sample: the transcript is transported by protocol duality, the special coordinate is
reversed, and the before/after windows are exchanged and reversed. -/
theorem rawZVariable_dualProtocol_dualHardSample
    (p : ProtocolType n)
    (ω : HardSample n) :
    rawZVariable n (dualProtocol n p) (dualHardSample n ω) =
      dualRawZValue n p (rawZVariable n p ω) := by
  apply RawZType.ext
  · exact message_dualProtocol_dualHardSample n p ω
  · simp [rawZVariable, dualRawZValue, specialCoordinate, dualHardSample]
  · simpa [rawZVariable, dualRawZValue] using xBeforeSpecial_dualHardSample n ω
  · simpa [rawZVariable, dualRawZValue] using yAfterSpecial_dualHardSample n ω

/-- Dualize an achievable `Z = (M,T,X_<T,Y_>T)` value by recoding the transcript and coarse
conditioning data. -/
noncomputable def dualZValue
    (p : ProtocolType n)
    (z : ZType n p) :
    ZType n (dualProtocol n p) :=
  ⟨dualRawZValue n p z.raw, by
    rcases z.achievable with ⟨ω, hω⟩
    refine ⟨dualHardSample n ω, ?_⟩
    rw [rawZVariable_dualProtocol_dualHardSample]
    exact congrArg (dualRawZValue n p) hω⟩

/-- Raw `Z` dualization is injective: two raw `Z` records with the same dual are equal, since
each component of the dual determines the corresponding original component. -/
theorem dualRawZValue_injective
    (p : ProtocolType n) :
    Function.Injective (dualRawZValue n p) := by
  intro z z' h
  apply RawZType.ext
  · exact dualProtocolTranscriptMap_injective n p (congrArg RawZType.transcript h)
  · have hT := congrArg RawZType.specialCoordinate h
    have hT' := congrArg Fin.rev hT
    simpa [dualRawZValue] using hT'
  · exact reverseBoolVector_injective n (congrArg RawZType.yAfter h)
  · exact reverseBoolVector_injective n (congrArg RawZType.xBefore h)

/-- The `Z`-value recoding induced by protocol and hard-sample duality is injective. -/
theorem dualZValue_injective
    (p : ProtocolType n) :
    Function.Injective (dualZValue n p) := by
  intro z z' h
  apply Subtype.ext
  exact dualRawZValue_injective n p (congrArg Subtype.val h)

/-- The `Z` variable for the dual protocol and hard sample is the recoded original `Z`. -/
theorem zVariable_dualProtocol_dualHardSample
    (p : ProtocolType n)
    (ω : HardSample n) :
    zVariable n (dualProtocol n p) (dualHardSample n ω) =
      dualZValue n p (zVariable n p ω) := by
  apply Subtype.ext
  exact rawZVariable_dualProtocol_dualHardSample n p ω

/-- Pulling a recoded dual `Z` fiber back along hard-sample duality gives the original `Z`
fiber. -/
theorem zVariable_dualProtocol_preimage_dualZValue
    (p : ProtocolType n)
    (z : ZType n p) :
    (dualHardSample n) ⁻¹'
        (zFiber n (dualProtocol n p) (dualZValue n p z)) =
      zFiber n p z := by
  ext ω
  change zVariable n (dualProtocol n p) (dualHardSample n ω) = dualZValue n p z ↔
    zVariable n p ω = z
  rw [zVariable_dualProtocol_dualHardSample]
  exact (dualZValue_injective n p).eq_iff

/-- The ambient hard-sample measure gives corresponding original and dual `Z` fibers the same
mass. -/
theorem volume_zVariable_dualProtocol_dualZValue
    (p : ProtocolType n)
    (z : ZType n p) :
    volume
        (zFiber n (dualProtocol n p) (dualZValue n p z)) =
      volume (zFiber n p z) := by
  let μ : Measure (HardSample n) := volume
  let S : Set (HardSample n) :=
    zFiber n (dualProtocol n p) (dualZValue n p z)
  have hpre :
      μ ((dualHardSample n) ⁻¹' S) = μ S :=
    Measure.measure_preimage_of_map_eq_self
      (volume_measurePreserving_dualHardSample n).map_eq
      MeasurableSet.of_discrete.nullMeasurableSet
  rw [← hpre]
  exact congrArg (fun S : Set (HardSample n) => μ S)
    (zVariable_dualProtocol_preimage_dualZValue n p z)

/-- The uniform hard-sample measure, as a real number, gives the `Z` fibre of the dual
protocol above the recoded value `dualZValue z` the same mass as the `Z` fibre of the
original protocol above `z`. This is the real-valued form of
`volume_zVariable_dualProtocol_dualZValue`. -/
theorem volume_measureReal_zVariable_dualProtocol_dualZValue
    (p : ProtocolType n)
    (z : ZType n p) :
    volume.real
        (zFiber n (dualProtocol n p) (dualZValue n p z)) =
      volume.real (zFiber n p z) := by
  repeat rw [Measure.real]
  rw [volume_zVariable_dualProtocol_dualZValue]

/-- Probabilities under the hard input distribution can be computed on the explicit hard sample
space by taking preimages under `input`. -/
theorem inputDist_measureReal_eq_preimage (S : Set (Set (Fin n) × Set (Fin n))) :
    letI := inputDist n
    volume.real S =
      volume.real ((input n) ⁻¹' S : Set (HardSample n)) := by
  change
    (inputMeasure n).real S =
      volume.real ((input n) ⁻¹' S : Set (HardSample n))
  rw [inputMeasure]
  rw [Measure.real]
  rw [Measure.map_apply Measurable.of_discrete MeasurableSet.of_discrete]
  rfl

/-- The set of hard samples on which a deterministic protocol outputs a value different from
the disjointness of the generated input pair. Its probability is the protocol error on
`A, B` assumed to be at most `1/32` in [RY20, Ch. 6, 'Assume the protocol error on A, B is
at most 1/32']. -/
def protocolErrorEvent
    (p : ProtocolType n) : Set (HardSample n) :=
  {ω | p.run (X n ω) (Y n ω) ≠ disjointness n (X n ω) (Y n ω)}

/-- The distributional error of a deterministic protocol for disjointness under the hard input
distribution equals the probability, under the uniform law on hard samples, of the event
`protocolErrorEvent`. This identifies the error assumed in [RY20, Ch. 6, 'Assume the
protocol error on A, B is at most 1/32'] with an event on the explicit sample space. -/
theorem distributionalError_inputDist_eq_protocolErrorEvent
    (p : ProtocolType n) :
  p.distributionalError (inputDist n) (disjointness n) =
      volume.real (protocolErrorEvent n p) := by
  rw [Deterministic.Protocol.distributionalError]
  letI := inputDist n
  change volume.real
      {xy : Set (Fin n) × Set (Fin n) | p.run xy.1 xy.2 ≠ disjointness n xy.1 xy.2} =
    volume.real (protocolErrorEvent n p)
  rw [inputDist_measureReal_eq_preimage]
  rfl

end RandomizedLowerBound

end Functions.Disjointness

end CommunicationComplexity
