/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7ce72dbb-d21b-4a66-8e02-d31efa956450

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We formalized the notion of Boolean circuits, k-wise independence, and sandwiching polynomials.
We proved that if a function can be sandwiched by polynomials of degree k with error ε, then any k-wise independent distribution fools the function with error ε (`Sandwiching_Implies_Fooling`).
We defined the `BravermanProperty` which states that AC0 circuits have sandwiching polynomials of polylogarithmic degree.
Finally, we proved `Braverman_Theorem`, which states that assuming the `BravermanProperty`, polylogarithmic independence fools AC0 circuits.
Specifically, for any depth d and size m, and any ε ≤ 1, there exists k = O(log(m/ε)^(c*d)) such that k-wise independence fools circuits of depth d and size m with error ε.
For ε > 1, the result holds trivially with k=0.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of a Boolean circuit with n inputs.
-/
inductive Circuit (n : ℕ)
| input : Fin n → Circuit n
| const : Bool → Circuit n
| not : Circuit n → Circuit n
| and : List (Circuit n) → Circuit n
| or : List (Circuit n) → Circuit n

/-
Size of a Boolean circuit.
-/
def Circuit.size {n : ℕ} : Circuit n → ℕ
| input _ => 1
| const _ => 1
| not c => c.size + 1
| and cs => (cs.map size).sum + 1
| or cs => (cs.map size).sum + 1
decreasing_by
simp +zetaDelta at *; (
rename_i c hc;
induction' cs with cs ih generalizing c <;> simp_all +decide [ List.length ];
grind); (
rename_i c hc;
induction' cs with cs ih generalizing c <;> simp_all +decide [ List.length ];
grind)

/-
Depth of a Boolean circuit.
-/
def Circuit.depth {n : ℕ} : Circuit n → ℕ
| input _ => 0
| const _ => 0
| not c => c.depth + 1
| and cs => (cs.map depth).maximum.getD 0 + 1
| or cs => (cs.map depth).maximum.getD 0 + 1
decreasing_by
aesop; (
-- Since $c$ is an element of $cs$, we can apply the induction hypothesis to $cs$.
have h_ind : ∀ {l : List (Circuit n)}, ‹Circuit n› ∈ l → (SizeOf.sizeOf ‹Circuit n›) < (SizeOf.sizeOf (Circuit.and l)) := by
  -- By definition of on毛泽społec, we have$stmt.SIZE.Carry marginBottom</think>
  intros l hl
  induction l <;> simp_all +decide [ Circuit.size ];
  grind;
exact h_ind ‹_›); (
induction cs <;> simp_all +arith +decide [ Circuit.rec ];
grind)

/-
Evaluation of a Boolean circuit.
-/
def Circuit.eval {n : ℕ} (x : Fin n → Bool) : Circuit n → Bool
| input i => x i
| const b => b
| not c => !c.eval x
| and cs => cs.attach.all (fun ⟨c, _⟩ => c.eval x)
| or cs => cs.attach.any (fun ⟨c, _⟩ => c.eval x)

/-
Definition of k-wise independence for a distribution on the hypercube.
-/
def IsKWiseIndependent {n : ℕ} (k : ℕ) (μ : PMF (Fin n → Bool)) : Prop :=
  ∀ (S : Finset (Fin n)), S.card ≤ k →
    μ.map (fun x => fun (i : S) => x i) = PMF.uniformOfFintype (S → Bool)

/-
Definition of what it means for k-wise independence to fool a set of circuits.
-/
noncomputable def Circuit.prob {n : ℕ} (C : Circuit n) (μ : PMF (Fin n → Bool)) : ℝ :=
  ∑ x : Fin n → Bool, if C.eval x then (μ x).toReal else 0

def Fools {n : ℕ} (k : ℕ) (ε : ℝ) (S : Set (Circuit n)) : Prop :=
  ∀ (μ : PMF (Fin n → Bool)), IsKWiseIndependent k μ →
  ∀ C ∈ S, |C.prob μ - C.prob (PMF.uniformOfFintype (Fin n → Bool))| ≤ ε

/-
Definition of Monomial and Polynomial, and the lemma that k-wise independence fools monomials of size at most k.
-/
def Monomial {n : ℕ} (S : Finset (Fin n)) (x : Fin n → Bool) : ℝ :=
  ∏ i ∈ S, if x i then 1 else 0

def IsPolynomial {n : ℕ} (d : ℕ) (P : (Fin n → Bool) → ℝ) : Prop :=
  ∃ (coeff : Finset (Fin n) → ℝ), (∀ S, S.card > d → coeff S = 0) ∧
  (∀ x, P x = ∑ S, coeff S * Monomial S x)

theorem KWise_Fools_Monomial {n k : ℕ} {μ : PMF (Fin n → Bool)} (hμ : IsKWiseIndependent k μ)
    (S : Finset (Fin n)) (hS : S.card ≤ k) :
    ∑ x, Monomial S x * (μ x).toReal = ∑ x, Monomial S x * (PMF.uniformOfFintype _ x).toReal := by
      have := hμ S hS; simp_all +decide [ PMF.uniformOfFintype_apply ] ; (
      convert congr_arg ( fun p : PMF ( S → Bool ) => ∑ x : S → Bool, if x = ( fun _ => Bool.true ) then ( p x |> ENNReal.toReal ) else 0 ) this using 1 <;> norm_num [ Monomial ] ; ring;
      · rw [ tsum_eq_sum ];
        any_goals exact Finset.univ.filter fun x => ∀ i ∈ S, x i = Bool.true;
        · rw [ Finset.sum_filter ] ; ring;
          rw [ ENNReal.toReal_sum ];
          · congr! 1;
            split_ifs <;> simp_all +decide [ funext_iff ];
            exact Or.inl <| Finset.prod_eq_zero ( Classical.choose_spec ‹∃ x ∈ S, _› |>.1 ) <| if_neg <| by simpa [ Classical.choose_spec ‹∃ x ∈ S, _› |>.2 ] ;
          · exact fun _ _ => by split_ifs <;> simp +decide [ PMF.apply_ne_top ] ;
        · simp +contextual [ funext_iff ];
      · field_simp;
        rw [ ← Finset.sum_div _ _ _, div_mul_eq_mul_div, div_eq_iff ] <;> norm_cast <;> norm_num [ Finset.card_univ ] ; ring;
        -- The sum $\sum_{x : \text{Fin } n \to \text{Bool}} \prod_{i \in S} \mathbf{1}_{x_i = \text{true}}$ counts the number of functions $x$ such that $x_i = \text{true}$ for all $i \in S$.
        have h_count : ∑ x : Fin n → Bool, (∏ i ∈ S, if x i then 1 else 0) = 2^(n - S.card) := by
          have h_sum_indicator : ∑ x : Fin n → Bool, (∏ i ∈ S, if x i = Bool.true then 1 else 0) = ∑ x : Finset (Fin n), if S ⊆ x then 1 else 0 := by
            refine' Finset.sum_bij ( fun x _ => Finset.univ.filter fun i => x i = Bool.true ) _ _ _ _ <;> simp +decide [ Finset.subset_iff ];
            · intro a₁ a₂ h; ext i; replace h := Finset.ext_iff.mp h i; aesop;
            · exact fun b => ⟨ fun i => if i ∈ b then Bool.true else Bool.false, by ext; aesop ⟩;
            · intro a; split_ifs <;> simp_all +decide [ Finset.prod_eq_zero_iff ] ;
          have h_card : Finset.card (Finset.filter (fun x => S ⊆ x) (Finset.powerset (Finset.univ : Finset (Fin n)))) = Finset.card (Finset.powerset (Finset.univ \ S)) := by
            refine' Finset.card_bij ( fun x hx => x \ S ) _ _ _ <;> simp_all +decide [ Finset.subset_iff ];
            · intro a₁ ha₁ a₂ ha₂ h; ext x; by_cases hx : x ∈ S <;> simp_all +decide [ Finset.ext_iff ] ;
            · exact fun b hb => ⟨ b ∪ S, by aesop_cat, by aesop_cat ⟩;
          simp_all +decide [ Finset.card_sdiff ];
        rw [ h_count, ← pow_add, Nat.sub_add_cancel ( show S.card ≤ n from le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ) ])

/-
k-wise independence fools polynomials of degree at most k.
-/
theorem KWise_Fools_Polynomial {n k : ℕ} {μ : PMF (Fin n → Bool)} (hμ : IsKWiseIndependent k μ)
    (P : (Fin n → Bool) → ℝ) (hP : IsPolynomial k P) :
    ∑ x, P x * (μ x).toReal = ∑ x, P x * (PMF.uniformOfFintype _ x).toReal := by
      obtain ⟨coeff, hcoeff⟩ := hP;
      simp +decide [ hcoeff, Finset.sum_mul _ _ _, Monomial ];
      rw [ Finset.sum_comm ];
      rw [ Finset.sum_congr rfl ];
      rw [ Finset.sum_comm ];
      intro S hS;
      by_cases hS_card : S.card ≤ k;
      · convert congr_arg ( fun x : ℝ => coeff S * x ) ( KWise_Fools_Monomial hμ S hS_card ) using 1 <;> norm_num [ Finset.sum_mul _ _ _ ];
        · simp +decide only [mul_assoc, Finset.mul_sum _ _ _];
          rfl;
        · simp +decide [ Finset.mul_sum _ _ _, mul_assoc, Monomial ];
      · aesop

/-
Definition of sandwiching polynomials.
-/
def SandwichingPolynomials {n : ℕ} (f : (Fin n → Bool) → ℝ) (k : ℕ) (ε : ℝ) : Prop :=
  ∃ (Pl Pu : (Fin n → Bool) → ℝ),
    IsPolynomial k Pl ∧ IsPolynomial k Pu ∧
    (∀ x, Pl x ≤ f x) ∧ (∀ x, f x ≤ Pu x) ∧
    (∑ x, (Pu x - Pl x) * (PMF.uniformOfFintype _ x).toReal) ≤ ε

/-
Theorem: If f has sandwiching polynomials of degree k with error ε, then any k-wise independent distribution fools f with error ε.
-/
theorem Sandwiching_Implies_Fooling {n k : ℕ} {f : (Fin n → Bool) → ℝ} {ε : ℝ}
    (h_sand : SandwichingPolynomials f k ε)
    (μ : PMF (Fin n → Bool)) (hμ : IsKWiseIndependent k μ) :
    abs ((∑ x, f x * (μ x).toReal) - (∑ x, f x * (PMF.uniformOfFintype _ x).toReal)) ≤ ε := by
      obtain ⟨ Pl, Pu, hPl, hPu, hLe, hGe, hε ⟩ := h_sand;
      -- By linearity of expectation, we can break this down into the expected difference between the upper and lower bounds.
      have h_exp_diff : ∑ x, f x * (μ x).toReal - ∑ x, f x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal ≤ ∑ x, Pu x * (μ x).toReal - ∑ x, Pl x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal ∧ ∑ x, f x * (μ x).toReal - ∑ x, f x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal ≥ ∑ x, Pl x * (μ x).toReal - ∑ x, Pu x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal := by
        constructor <;> rw [ ← Finset.sum_sub_distrib ] <;> rw [ ← Finset.sum_sub_distrib ] <;> gcongr <;> aesop;
      -- By the properties of k-wise independence, we know that the expected value of Pl and Pu under μ is equal to their expected value under the uniform distribution.
      have h_exp_eq : ∑ x, Pl x * (μ x).toReal = ∑ x, Pl x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal ∧ ∑ x, Pu x * (μ x).toReal = ∑ x, Pu x * ((PMF.uniformOfFintype (Fin n → Bool)) x).toReal := by
        exact ⟨ KWise_Fools_Polynomial hμ Pl hPl, KWise_Fools_Polynomial hμ Pu hPu ⟩;
      simp_all +decide [ sub_mul ];
      exact abs_le.mpr ⟨ by linarith, by linarith ⟩

/-
Definition of the Braverman Property: AC0 circuits have sandwiching polynomials of polylogarithmic degree.
-/
def BravermanProperty : Prop :=
  ∃ (c : ℝ), c > 0 ∧ ∀ (n d m : ℕ) (ε : ℝ), 0 < ε → m ≥ 1 →
    ∀ C : Circuit n, C.depth ≤ d → C.size ≤ m →
      SandwichingPolynomials (fun x => if C.eval x then 1 else 0) (Nat.ceil ((Real.log (m / ε) + 2) ^ (c * d))) ε

/-
Helper lemma: The ceiling of B^E is bounded by B^((c+1)d).
-/
lemma Braverman_Bound_Helper (m d : ℕ) (ε c : ℝ) (hm : m ≥ 1) (hε : 0 < ε) (hε1 : ε ≤ 1) (hc : c > 0) :
  let B := Real.log (m / ε) + 2
  let E := c * d
  let k := Nat.ceil (B ^ E)
  (k : ℝ) ≤ B ^ ((c + 1) * d) := by
    rcases d with ( _ | d ) <;> norm_num at *;
    have h_log : Real.log (m / ε) ≥ 0 := by
      exact Real.log_nonneg ( by rw [ le_div_iff₀ hε ] ; linarith [ show ( m : ℝ ) ≥ 1 by norm_cast ] );
    refine' le_trans ( Nat.ceil_lt_add_one ( by positivity ) |> le_of_lt ) _;
    rw [ show ( c + 1 ) * ( d + 1 ) = c * ( d + 1 ) + ( d + 1 ) by ring, Real.rpow_add ] <;> try positivity;
    refine' le_trans _ ( mul_le_mul_of_nonneg_left ( Real.rpow_le_rpow_of_exponent_le ( by linarith ) ( show ( d : ℝ ) + 1 ≥ 1 by linarith ) ) ( by positivity ) ) ; norm_cast ; norm_num;
    nlinarith [ show 1 ≤ ( Real.log ( m / ε ) + 2 ) ^ ( c * ( d + 1 ) ) by exact Real.one_le_rpow ( by linarith ) ( by positivity ) ]

/-
Lemma: The probability of a circuit accepting is at most 1.
-/
lemma Circuit.prob_le_one {n : ℕ} (C : Circuit n) (μ : PMF (Fin n → Bool)) : C.prob μ ≤ 1 := by
  refine' le_trans ( Finset.sum_le_sum _ ) _;
  exact fun x => ( μ x |> ENNReal.toReal );
  · aesop;
  · rw [ ← ENNReal.toReal_sum ];
    · rw [ ← ENNReal.toReal_one, ← μ.tsum_coe ];
      rw [ tsum_fintype ];
    · exact fun x _ => μ.apply_ne_top x

/-
Lemma: The probability of a circuit accepting is non-negative.
-/
lemma Circuit.prob_nonneg {n : ℕ} (C : Circuit n) (μ : PMF (Fin n → Bool)) : 0 ≤ C.prob μ := by
  exact Finset.sum_nonneg fun x _ => by aesop;

/-
Lemma: If ε > 1, then 0-wise independence fools any set of circuits (trivially).
-/
lemma Fools_zero_of_eps_gt_one {n : ℕ} {ε : ℝ} (hε : ε > 1) (S : Set (Circuit n)) :
  Fools 0 ε S := by
    intro μ hμ C hC;
    refine' le_trans ( abs_sub_le_iff.mpr ⟨ _, _ ⟩ ) hε.le;
    · refine' le_trans ( sub_le_self _ ( _ ) ) _;
      · exact?;
      · exact?;
    · exact sub_le_iff_le_add'.mpr ( le_trans ( Circuit.prob_le_one _ _ ) ( by linarith [ show 0 ≤ C.prob μ from by exact? ] ) )

/-
Lemma: Circuit probability is equal to the sum of the indicator function times the probability mass.
-/
lemma Circuit.prob_eq_sum {n : ℕ} (C : Circuit n) (μ : PMF (Fin n → Bool)) :
  C.prob μ = ∑ x, (if C.eval x then 1 else 0) * (μ x).toReal := by
  unfold Circuit.prob
  apply Finset.sum_congr rfl
  intro x hx
  split_ifs <;> simp

/-
Main Theorem: Assuming the Braverman Property (AC0 has sandwiching polynomials), polylogarithmic independence fools AC0 circuits (for ε ≤ 1).
-/
theorem Braverman_Theorem (hB : BravermanProperty) :
  ∃ (c : ℝ), c > 0 ∧ ∀ (n d m : ℕ) (ε : ℝ), 0 < ε → ε ≤ 1 → m ≥ 1 →
    ∃ k : ℕ, (k : ℝ) ≤ (Real.log (m / ε) + 2) ^ (c * d) ∧
    Fools k ε {C : Circuit n | C.depth ≤ d ∧ C.size ≤ m} := by
  obtain ⟨cB, hcB_pos, hB_prop⟩ := hB
  use cB + 1
  constructor
  · linarith
  · intro n d m ε hε hε1 hm
    let B := Real.log (m / ε) + 2
    let E := cB * d
    let k := Nat.ceil (B ^ E)
    use k
    constructor
    · apply Braverman_Bound_Helper m d ε cB hm hε hε1 hcB_pos
    · intro μ hμ C hC
      obtain ⟨Pl, Pu, hPl, hPu, hPl_le, hPu_ge, h_sand⟩ := hB_prop n d m ε hε hm C hC.1 hC.2
      rw [Circuit.prob_eq_sum, Circuit.prob_eq_sum]
      apply Sandwiching_Implies_Fooling ⟨Pl, Pu, hPl, hPu, hPl_le, hPu_ge, h_sand⟩ μ hμ


