/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a9e6240c-cc9a-4bcc-a267-9408edaf0cfa

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib
import TCSlib.CodingTheory.Basic

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
open CodingTheory
open InnerProductSpace
open Codeword

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false


-- variable {𝔽 : Type*} [Field 𝔽] [Fintype 𝔽] [DecidableEq 𝔽]
variable {α : Type*} [Fintype α] [Nonempty α] [DecidableEq α] [Field α]-- the alphabet
variable {n k : ℕ}

/-
Lemma 3.1: Suppose v_1, ..., v_m are unit vectors in R^n such that <v_i, v_j> ≤ -ε for all i ≠ j. Then m ≤ 1 + 1/ε.
-/


theorem lemma_3_1 {m n : ℕ} {ε : ℝ} (hε : 0 < ε)
  (v : Fin m → EuclideanSpace ℝ (Fin n))
  (h_unit : ∀ i, ‖v i‖ = 1)
  (h_dot : ∀ i j, i ≠ j → inner ℝ (v i) (v j) ≤ -ε) :
  (m : ℝ) ≤ 1 + 1 / ε := by
    -- Consider the norm of the sum of these vectors:
    have h_norm : ‖∑ i, v i‖^2 = ∑ i, ∑ j, ⟪v i, v j⟫_ℝ := by
      rw [ ← real_inner_self_eq_norm_sq ];
      simp +decide only [inner_sum, sum_inner];
      exact Finset.sum_comm;
    -- Since $<v_i, v_j> \leq -ε$ for all $i \neq j$, we have $\sum_{i \neq j} <v_i, v_j> \leq -ε \cdot m(m-1)$.
    have h_sum_dot : ∑ i, ∑ j ∈ Finset.univ.erase i, ⟪v i, v j⟫_ℝ ≤ -ε * m * (m - 1) := by
      refine' le_trans ( Finset.sum_le_sum fun i hi => Finset.sum_le_sum fun j hj => h_dot i j <| by aesop ) _ ; norm_num ; ring_nf ; norm_num [ hε.ne' ] ;
      cases m <;> norm_num ; nlinarith;
    simp_all +decide [ inner_self_eq_norm_sq_to_K ];
    nlinarith [ inv_pos.2 hε, mul_inv_cancel₀ hε.ne', sq ( m : ℝ ) ]


def min_distance (C : Code n α) : ℕ :=
  if h : C.card < 2 then 0 else
  (C.product C).filter (fun x ↦ x.1 ≠ x.2) |>.image (fun x ↦ hammingDist x.1 x.2) |>.min' (by
  obtain ⟨ x, hx, y, hy, hxy ⟩ := Finset.one_lt_card.1 ( by linarith ) ; exact ⟨ _, Finset.mem_image.2 ⟨ ( x, y ), Finset.mem_filter.2 ⟨ Finset.mem_product.2 ⟨ hx, hy ⟩, hxy ⟩, rfl ⟩ ⟩)

def is_distance_at_least (C : Code n α) (d : ℕ) : Prop :=
  ∀ c1 ∈ C, ∀ c2 ∈ C, c1 ≠ c2 → hammingDist c1 c2 ≥ d

def is_constant_weight (C : Code n α) (w : ℕ) : Prop :=
  ∀ c ∈ C, weight c = w

def is_bounded_weight (C : Code n α) (w : ℕ) : Prop :=
  ∀ c ∈ C, weight c ≤ w

/-
A_q(n, d) is the maximum size of a code of length n and minimum distance d.
-/
noncomputable def A_q (n d : ℕ) (α : Type*) [Fintype α] [DecidableEq α] : ℕ :=
  (Finset.univ : Finset (Code n α)).filter (fun C ↦ is_distance_at_least C d) |>.image Finset.card |>.max' (by
  -- The empty set is a code with minimum distance d, so its cardinality is 0.
  use 0
  simp [is_distance_at_least])

/-
A_q(n, d, w) is the maximum size of a constant weight code of length n, minimum distance d, and weight w.
-/
noncomputable def A_q_w (n d w : ℕ) (α : Type*) [Fintype α] [DecidableEq α] [Field α] : ℕ :=
  (Finset.univ : Finset (Code n α)).filter (fun C ↦ is_distance_at_least C d ∧ is_constant_weight C w) |>.image Finset.card |>.max' (by
  use 0
  simp [is_distance_at_least, is_constant_weight])

/-
A0_q(n, d, w) is the maximum size of a code of length n, minimum distance d, and weight at most w.
-/
noncomputable def A0_q_w (n d w : ℕ) (α : Type*) [Fintype α] [DecidableEq α] [Field α] : ℕ :=
  (Finset.univ : Finset (Code n α)).filter (fun C ↦ is_distance_at_least C d ∧ is_bounded_weight C w) |>.image Finset.card |>.max' (by
  use 0
  simp [is_distance_at_least, is_bounded_weight])

/-
Exercise 2: Prove that A_q(n, d) ≤ (q^n / (choose(n, w) * (q-1)^w)) * A_q(n, d, w).
-/
theorem exercise_2 {n d w : ℕ} {α : Type*} [Fintype α] [DecidableEq α] [Field α] (h_w : w ≤ n) :
  (A_q n d α : ℝ) ≤ (Fintype.card α ^ n : ℝ) / (Nat.choose n w * (Fintype.card α - 1) ^ w) * A_q_w n d w α := by
    -- Let $C$ be a code of size $A_q(n, d)$.
    obtain ⟨C, hC⟩ : ∃ C : Code n α, is_distance_at_least C d ∧ Finset.card C = A_q n d α := by
      have := Finset.max'_mem ( Finset.image Finset.card ( Finset.filter ( fun C => is_distance_at_least C d ) ( Finset.univ : Finset ( Code n α ) ) ) ) ⟨ 0, Finset.mem_image_of_mem _ ( Finset.mem_filter.mpr ⟨ Finset.mem_univ ∅, by simp +decide [ is_distance_at_least ] ⟩ ) ⟩ ; aesop;
    -- Let $S$ be the set of pairs $(c, x)$ where $c \in C$ and $d(c, x) = w$.
    set S := Finset.filter (fun (p : Codeword n α × Codeword n α) => hammingDist p.1 p.2 = w) (C.product (Finset.univ : Finset (Codeword n α))) with hS_def
    have hS_card : S.card = Finset.card C * Nat.choose n w * ((Fintype.card α) - 1) ^ w := by
      have hS_card : ∀ c ∈ C, Finset.card (Finset.filter (fun x => hammingDist c x = w) (Finset.univ : Finset (Codeword n α))) = Nat.choose n w * ((Fintype.card α) - 1) ^ w := by
        intro c hc
        have h_sphere : Finset.card (Finset.filter (fun x => hammingDist c x = w) (Finset.univ : Finset (Codeword n α))) = Finset.card (Finset.biUnion (Finset.powersetCard w (Finset.univ : Finset (Fin n))) (fun s => Finset.image (fun f : s → α => fun i => if h : i ∈ s then f ⟨i, h⟩ else c i) (Finset.univ.filter (fun f : s → α => ∀ i : s, f i ≠ c i)))) := by
          congr with x ; simp +decide [ hammingDist ];
          constructor;
          · intro hx
            use Finset.univ.filter (fun i => ¬c i = x i);
            refine' ⟨ hx, fun ⟨ i, hi ⟩ => x i, _, _ ⟩ <;> aesop;
          · rintro ⟨ s, hs, f, hf, rfl ⟩;
            rw [ Finset.card_filter ];
            rw [ ← Finset.sum_subset ( Finset.subset_univ s ) ];
            · rw [ Finset.sum_congr rfl fun x hx => if_pos <| by specialize hf x hx; aesop ] ; aesop;
            · grind;
        rw [ h_sphere, Finset.card_biUnion ];
        · rw [ Finset.sum_congr rfl fun s hs => Finset.card_image_of_injective _ fun f g hfg => _ ];
          · -- The number of functions from a set of size $w$ to a set of size $q-1$ is $(q-1)^w$.
            have h_card_functions : ∀ s : Finset (Fin n), s.card = w → Finset.card (Finset.filter (fun f : s → α => ∀ i : s, f i ≠ c i) (Finset.univ : Finset (s → α))) = (Fintype.card α - 1) ^ w := by
              intro s hs_card
              have h_card_functions : Finset.card (Finset.filter (fun f : s → α => ∀ i : s, f i ≠ c i) (Finset.univ : Finset (s → α))) = Finset.card (Finset.pi s (fun _ => Finset.univ.filter (fun x => x ≠ c (↑‹Fin n›)))) := by
                refine' Finset.card_bij _ _ _ _;
                use fun f hf i hi => f ⟨ i, hi ⟩;
                · simp +contextual [ Finset.mem_pi ];
                · simp +contextual [ funext_iff ];
                · simp +decide [ funext_iff ];
                  exact fun b hb => ⟨ fun x => b x x.2, fun x hx => hb x hx, fun x hx => rfl ⟩;
              simp_all +decide [ Finset.card_univ, Finset.filter_ne' ];
            rw [ Finset.sum_congr rfl fun s hs => h_card_functions s <| Finset.mem_powersetCard.mp hs |>.2 ] ; simp +decide [ Finset.card_univ ];
          · intro s hs f g hfg; ext ⟨ i, hi ⟩ ; replace hfg := congr_fun hfg i; aesop;
        · intro s hs t ht hst; simp_all +decide [ Finset.disjoint_left ] ;
          intro a ha x hx h; contrapose! hst; ext i; simp_all +decide [ funext_iff ] ;
          grind +ring;
      have hS_card : S.card = Finset.sum C (fun c => Finset.card (Finset.filter (fun x => hammingDist c x = w) (Finset.univ : Finset (Codeword n α)))) := by
        erw [ Finset.card_filter ] ; erw [ Finset.sum_product ] ; aesop;
      rw [ hS_card, Finset.sum_congr rfl ‹_›, Finset.sum_const, smul_eq_mul, mul_assoc ];
    -- For each $x \in \alpha^n$, let $N(x)$ be the number of codewords $c \in C$ such that $d(c, x) = w$.
    have hN_card : ∀ x : Codeword n α, (Finset.filter (fun c => hammingDist c x = w) C).card ≤ A_q_w n d w α := by
      intro x
      have hN_x : is_constant_weight (Finset.image (fun c => c - x) (Finset.filter (fun c => hammingDist c x = w) C)) w := by
        intro c hc
        obtain ⟨c', hc', rfl⟩ : ∃ c' ∈ Finset.filter (fun c => hammingDist c x = w) C, c = c' - x := by
          grind
        have h_weight : weight (c' - x) = w := by
          simp_all +decide [ weight, hammingDist, hamming_distance ];
          simpa only [ sub_eq_zero ] using hc'.2
        exact h_weight
      have hN_x_dist : is_distance_at_least (Finset.image (fun c => c - x) (Finset.filter (fun c => hammingDist c x = w) C)) d := by
        intro c hc c' hc' hne; simp_all +decide [ is_distance_at_least, hammingDist ] ; (
        rcases hc with ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩ ; rcases hc' with ⟨ b, ⟨ hb₁, hb₂ ⟩, rfl ⟩ ; simp_all +decide [ sub_eq_iff_eq_add ] ;);
      have hN_x_card : (Finset.image (fun c => c - x) (Finset.filter (fun c => hammingDist c x = w) C)).card ≤ A_q_w n d w α := by
        refine' Finset.le_max' _ _ _ ; aesop;
      have hN_x_card_eq : (Finset.filter (fun c => hammingDist c x = w) C).card = (Finset.image (fun c => c - x) (Finset.filter (fun c => hammingDist c x = w) C)).card := by
        rw [ Finset.card_image_of_injective _ fun a b h => by simpa using h ]
      linarith [hN_x_card, hN_x_card_eq];
    -- Therefore, $|S| \leq \sum_{x \in \alpha^n} A_q(n, d, w) = q^n A_q(n, d, w)$.
    have hS_card_le : S.card ≤ (Fintype.card α) ^ n * A_q_w n d w α := by
      have hS_card_le : S.card = Finset.sum (Finset.univ : Finset (Codeword n α)) (fun x => (Finset.filter (fun c => hammingDist c x = w) C).card) := by
        rw [ show S = Finset.biUnion ( Finset.univ : Finset ( Codeword n α ) ) ( fun x => Finset.image ( fun c => ( c, x ) ) ( Finset.filter ( fun c => hammingDist c x = w ) C ) ) from ?_, Finset.card_biUnion ];
        · exact Finset.sum_congr rfl fun _ _ => Finset.card_image_of_injective _ fun _ _ h => by injection h;
        · exact fun x _ y _ hxy => Finset.disjoint_left.mpr fun p hp hp' => hxy <| by aesop;
        · ext ⟨c, x⟩; simp [hS_def];
      exact hS_card_le.symm ▸ le_trans ( Finset.sum_le_sum fun _ _ => hN_card _ ) ( by simp +decide [ Finset.card_univ ] );
    rcases k : Fintype.card α with ( _ | _ | k ) <;> simp_all +decide [ div_mul_eq_mul_div ];
    · exact absurd k ( Nat.ne_of_gt ( Fintype.one_lt_card ) );
    · rw [ le_div_iff₀ ( mul_pos ( Nat.cast_pos.mpr ( Nat.choose_pos h_w ) ) ( by positivity ) ) ] ; norm_cast at * ; linarith;

/-
For any code C with minimum distance d and any vector x, the number of codewords at distance w from x is at most A_q(n, d, w).
-/
lemma exercise_2_helper {n d w : ℕ} {α : Type*} [Fintype α] [DecidableEq α] [Field α] (C : Code n α) (hC : is_distance_at_least C d) (x : Codeword n α) :
  (C.filter (fun c => hammingDist c x = w)).card ≤ A_q_w n d w α := by
    -- Let $C_x = \{c - x \mid c \in C, d(c, x) = w\}$.
    set C_x := Finset.image (fun c => fun i => c i - x i) (Finset.filter (fun c => hammingDist c x = w) C) with hC_x_def;
    -- Then for any $c_1, c_2 \in C_x$, $c_1 - c_2 = (c'_1 - x) - (c'_2 - x) = c'_1 - c'_2$, so the distance is preserved.
    have hC_x_dist : is_distance_at_least C_x d := by
      intro c1 hc1 c2 hc2 hne; simp_all +decide [ is_distance_at_least ] ;
      obtain ⟨ a, ⟨ ha1, ha2 ⟩, rfl ⟩ := hc1; obtain ⟨ b, ⟨ hb1, hb2 ⟩, rfl ⟩ := hc2; specialize hC a ha1 b hb1; simp_all +decide [ hammingDist ] ;
      exact hC ( by contrapose! hne; ext i; simp +decide [ hne ] )
    have hC_x_const : is_constant_weight C_x w := by
      intro c hc; obtain ⟨ c', hc', rfl ⟩ := Finset.mem_image.mp hc; simp_all +decide [ is_constant_weight ] ;
      convert hc'.2 using 1;
      unfold weight hamming_distance hammingDist
      simp +decide [ sub_eq_zero ] ;
    have hC_card : (Finset.filter (fun c => hammingDist c x = w) C).card = C_x.card := by
      rw [ Finset.card_image_of_injective _ fun a b h => by ext i; simpa using congr_fun h i ]
    have hC_x_le_A_q_w : C_x.card ≤ A_q_w n d w α := by
      refine' Finset.le_max' _ _ _ ; aesop
    linarith [hC_card, hC_x_le_A_q_w]

/-
Exercise 2: Prove that A_q(n, d) ≤ (q^n / (choose(n, w) * (q-1)^w)) * A_q(n, d, w).
-/
theorem exercise_2_thm {n d w : ℕ} {α : Type*} [Fintype α] [DecidableEq α] [Field α] (h_w : w ≤ n) :
  (A_q n d α : ℝ) ≤ (Fintype.card α ^ n : ℝ) / (Nat.choose n w * (Fintype.card α - 1) ^ w) * A_q_w n d w α := by
    convert exercise_2 h_w using 1

/-
The Johnson radius J2(n, d) is (n - sqrt(n(n - 2d))) / 2.
-/
noncomputable def J2 (n d : ℕ) : ℝ := (n - Real.sqrt (n * (n - 2 * d))) / 2

/-
Projection step for Lemma 3.2: If v, w have non-positive inner product and non-positive inner products with a unit vector u, then their projections onto the orthogonal complement of u also have non-positive inner product.
-/
theorem lemma_3_2_projection_step {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V]
  (u v w : V) (hu : ‖u‖ = 1)
  (hvw : inner ℝ v w ≤ (0 : ℝ)) (hvu : inner ℝ v u ≤ (0 : ℝ)) (hwu : inner ℝ w u ≤ (0 : ℝ)) :
  let v' := v - (inner ℝ v u) • u
  let w' := w - (inner ℝ w u) • u
  inner ℝ v' w' ≤ (0 : ℝ) := by
    simp +decide [ inner_sub_left, inner_sub_right, inner_smul_left ];
    simp +decide [ inner_smul_right, inner_smul_left, hu ];
    simp +decide [ real_inner_comm, hu, inner_self_eq_norm_sq_to_K ] at * ; nlinarith [ mul_nonneg_of_nonpos_of_nonpos hvu hwu ]

/-
Lemma 3.2: Suppose v_1, ..., v_m are unit vectors in R^n such that <v_i, v_j> ≤ 0 for all i ≠ j. Then m ≤ 2n.
-/
theorem lemma_3_2 {m n : ℕ}
  (v : Fin m → EuclideanSpace ℝ (Fin n))
  (h_unit : ∀ i, ‖v i‖ = 1)
  (h_dot : ∀ i j, i ≠ j → inner ℝ (v i) (v j) ≤ (0 : ℝ)) :
  m ≤ 2 * n := by
    induction' n with n ih generalizing m;
    · simp_all +decide [ EuclideanSpace.norm_eq ];
      exact Nat.eq_zero_of_not_pos fun h => h_unit ⟨ 0, h ⟩;
    · rcases m with ( _ | _ | m ) <;> norm_num at *;
      · linarith;
      · -- Let $v_0$ be one of the vectors. Let $W$ be the orthogonal complement of $v_0$. $W$ has dimension $n$.
        set v0 := v 0
        set W := (Submodule.span ℝ {v0})ᗮ
        have hW_dim : Module.finrank ℝ W = n := by
          have := Submodule.finrank_add_finrank_orthogonal ( Submodule.span ℝ { v0 } );
          rw [ finrank_span_singleton ] at this <;> norm_num at *;
          · linarith!;
          · exact ne_of_apply_ne Norm.norm ( by aesop );
        -- For each $i \neq 0$, let $u_i$ be the projection of $v_i$ onto $W$. By `lemma_3_2_projection_step`, for $i, j \neq 0$, $\langle u_i, u_j \rangle \leq 0$.
        set u : Fin (m + 1) → EuclideanSpace ℝ (Fin (n + 1)) := fun i => v (Fin.succ i) - (inner ℝ (v (Fin.succ i)) v0) • v0
        have hu_unit : ∀ i, ‖u i‖ ≤ 1 := by
          intro i
          have hu_norm : ‖u i‖ ^ 2 = ‖v (Fin.succ i)‖ ^ 2 - (inner ℝ (v (Fin.succ i)) v0) ^ 2 := by
            rw [ @norm_sub_sq ℝ ];
            norm_num [ norm_smul, inner_smul_right ] ; ring;
            norm_num [ h_unit ] ; ring;
            grind;
          nlinarith [ h_unit ( Fin.succ i ), h_unit 0 ]
        have hu_dot : ∀ i j, i ≠ j → inner ℝ (u i) (u j) ≤ 0 := by
          intros i j hij
          have h_inner : inner ℝ (u i) (u j) ≤ 0 := by
            apply_rules [ lemma_3_2_projection_step ];
            · exact fun h => hij <| Fin.succ_injective _ h;
            · exact Fin.succ_ne_zero _;
            · exact Fin.succ_ne_zero _
          exact h_inner
        have hu_nonzero : ∀ i, u i ≠ 0 → ‖(‖u i‖⁻¹ • u i : EuclideanSpace ℝ (Fin (n + 1)))‖ = 1 := by
          simp +contextual [ norm_smul, hu_unit ]
        have hu_dot_nonzero : ∀ i j, u i ≠ 0 → u j ≠ 0 → i ≠ j → inner ℝ ((‖u i‖⁻¹ • u i : EuclideanSpace ℝ (Fin (n + 1)))) ((‖u j‖⁻¹ • u j : EuclideanSpace ℝ (Fin (n + 1))) ) ≤ 0 := by
          simp_all +decide [ inner_smul_left, inner_smul_right ];
          exact fun i j hi hj hij => mul_nonpos_of_nonneg_of_nonpos ( inv_nonneg.2 ( norm_nonneg _ ) ) ( mul_nonpos_of_nonneg_of_nonpos ( inv_nonneg.2 ( norm_nonneg _ ) ) ( hu_dot i j hij ) );
        -- Let $S$ be the set of indices $i$ such that $u_i \neq 0$.
        set S := Finset.filter (fun i => u i ≠ 0) Finset.univ
        have hS_card : S.card ≤ 2 * n := by
          -- By the induction hypothesis, the number of vectors in $W$ is at most $2n$.
          have h_ind : ∀ (w : Fin S.card → W), (∀ i, ‖w i‖ = 1) → (∀ i j, i ≠ j → inner ℝ (w i) (w j) ≤ 0) → S.card ≤ 2 * n := by
            intros w hw_unit hw_dot;
            contrapose! ih;
            -- Since $W$ is isomorphic to $\mathbb{R}^n$, we can use this isomorphism to map the vectors in $W$ to vectors in $\mathbb{R}^n$.
            obtain ⟨iso, h_iso⟩ : ∃ iso : W ≃ₗᵢ[ℝ] EuclideanSpace ℝ (Fin n), True := by
              refine' ⟨ _, trivial ⟩;
              have h_iso : Nonempty (W ≃ₗᵢ[ℝ] EuclideanSpace ℝ (Fin n)) := by
                have h_basis : ∃ (b : OrthonormalBasis (Fin n) ℝ W), True := by
                  simp +zetaDelta at *;
                  refine' ⟨ _ ⟩;
                  convert ( stdOrthonormalBasis ℝ ( Submodule.span ℝ { v 0 } )ᗮ );
                  exact hW_dim.symm
                exact ⟨ h_basis.choose.repr ⟩;
              exact h_iso.some;
            use S.card, fun i => iso (w i);
            simp_all +decide [ LinearIsometryEquiv.norm_map, LinearIsometryEquiv.inner_map_map ];
          contrapose! h_ind;
          obtain ⟨w, hw⟩ : ∃ w : Fin S.card → Fin (m + 1), StrictMono w ∧ ∀ i, u (w i) ≠ 0 := by
            exact ⟨ fun i => S.orderEmbOfFin rfl i, by simp +decide [ StrictMono ], fun i => Finset.mem_filter.mp ( S.orderEmbOfFin_mem rfl i ) |>.2 ⟩;
          use fun i => ⟨‖u (w i)‖⁻¹ • u (w i), by
            simp +zetaDelta at *;
            intro x hx; rw [ Submodule.mem_span_singleton ] at hx; obtain ⟨ k, rfl ⟩ := hx; simp +decide [ inner_smul_left, inner_smul_right ] ;
            simp +decide [ inner_sub_right, inner_smul_right, h_unit ];
            simp +decide [ real_inner_comm, h_unit ];
            simp +decide [ real_inner_self_eq_norm_sq, h_unit ]⟩;
          exact ⟨ fun i => by simpa [ Submodule.coe_norm ] using hu_nonzero ( w i ) ( hw.2 i ), fun i j hij => by simpa [ Submodule.coe_inner ] using hu_dot_nonzero ( w i ) ( w j ) ( hw.2 i ) ( hw.2 j ) ( hw.1.injective.ne hij ), h_ind ⟩;
        -- The indices not in $S$ correspond to $v_i = -v_0$. There is at most 1 such index.
        have h_neg_v0 : (Finset.univ.filter (fun i => u i = 0)).card ≤ 1 := by
          -- If $u_i = 0$, then $v_{i+1}$ is parallel to $v_0$. Since $\langle v_{i+1}, v_0 \rangle \leq 0$ and they are unit vectors, $v_{i+1} = -v_0$.
          have h_parallel : ∀ i, u i = 0 → v (Fin.succ i) = -v0 := by
            intro i hi
            have h_parallel : v (Fin.succ i) = (inner ℝ (v (Fin.succ i)) v0) • v0 := by
              exact eq_of_sub_eq_zero hi;
            have h_inner_neg : inner ℝ (v (Fin.succ i)) v0 ≤ 0 := by
              exact h_dot _ _ ( ne_of_gt ( Fin.succ_pos i ) );
            have h_inner_neg : inner ℝ (v (Fin.succ i)) v0 = -1 := by
              have := h_unit ( Fin.succ i ) ; rw [ h_parallel ] at this; norm_num [ norm_smul, h_unit ] at this;
              rw [ abs_of_nonpos h_inner_neg, h_unit ] at this ; linarith;
            simpa [ h_inner_neg ] using h_parallel;
          rw [ Finset.card_le_one_iff ];
          intro i j hi hj; have := h_parallel i ( Finset.mem_filter.mp hi |>.2 ) ; have := h_parallel j ( Finset.mem_filter.mp hj |>.2 ) ; simp_all +decide [ Fin.ext_iff ] ;
          contrapose! h_dot;
          use Fin.succ i, Fin.succ j; simp_all +decide [ Fin.ext_iff ] ;
          rw [ real_inner_self_eq_norm_sq ];
          exact sq_pos_of_pos ( h_unit 0 ▸ zero_lt_one );
        have := Finset.card_add_card_compl ( Finset.filter ( fun i => u i ≠ 0 ) Finset.univ ) ; norm_num at * ; linarith;

/-
The inner product of the vectors corresponding to two binary codewords c1 and c2 is n - 2 * hammingDist(c1, c2).
-/
theorem inner_product_calculation {n : ℕ} (c₁ c₂ : Codeword n (ZMod 2)) :
  let v₁ : EuclideanSpace ℝ (Fin n) := fun i => if c₁ i = 1 then -1 else 1
  let v₂ : EuclideanSpace ℝ (Fin n) := fun i => if c₂ i = 1 then -1 else 1
  inner ℝ v₁ v₂ = (n : ℝ) - 2 * (hammingDist c₁ c₂ : ℝ) := by
    unfold hammingDist;
    -- We can simplify the inner product expression by considering the cases where $c₁_i = c₂_i$ and $c₁_i \ne c₂_i$.
    have h_inner : ∀ i : Fin n, (if c₁ i = 1 then -1 else 1 : ℝ) * (if c₂ i = 1 then -1 else 1) = 1 - 2 * (if c₁ i ≠ c₂ i then 1 else 0 : ℝ) := by
      intro i; rcases c₁ i with ( _ | _ | c₁ ) <;> rcases c₂ i with ( _ | _ | c₂ ) <;> norm_num <;> tauto;
    convert Finset.sum_congr rfl fun i _ => h_inner i using 1 ; norm_num [ mul_comm, Finset.mul_sum _ _ _ ] ; ring;
    any_goals exact Finset.univ;
    · exact Finset.sum_congr rfl fun _ _ => by split_ifs <;> simp +decide [ * ] ;
    · simp +decide [ Finset.sum_ite ] ; ring

/-
Under the Johnson bound condition, the shifted vectors have non-positive inner product.
-/
theorem johnson_bound_inequality {n d w : ℕ} (h_w : w ≤ n) (h_d : d ≤ n)
  (h_w_le : w ≤ (n - Real.sqrt (n * (n - 2 * d))) / 2)
  (c₁ c₂ : Codeword n (ZMod 2)) (h_dist : hammingDist c₁ c₂ ≥ d)
  (h_w₁ : weight c₁ ≤ w) (h_w₂ : weight c₂ ≤ w) :
  let v₁ : EuclideanSpace ℝ (Fin n) := fun i => if c₁ i = 1 then -1 else 1
  let v₂ : EuclideanSpace ℝ (Fin n) := fun i => if c₂ i = 1 then -1 else 1
  let r : EuclideanSpace ℝ (Fin n) := fun _ => 1
  let α := Real.sqrt (n * (n - 2 * d)) / n
  let u₁ := v₁ - α • r
  let u₂ := v₂ - α • r
  inner ℝ u₁ u₂ ≤ (0 : ℝ) := by
    by_cases hn : n = 0 <;> simp_all +decide [ mul_assoc, mul_comm, mul_left_comm, inner_smul_left, inner_smul_right ];
    · aesop;
    · have h_inner_product : let v₁ : EuclideanSpace ℝ (Fin n) := fun i => if c₁ i = 1 then -1 else 1;
        let v₂ : EuclideanSpace ℝ (Fin n) := fun i => if c₂ i = 1 then -1 else 1;
        let r : EuclideanSpace ℝ (Fin n) := fun _ => 1;
        ⟪v₁, v₂⟫_ℝ = (n : ℝ) - 2 * (hammingDist c₁ c₂ : ℝ) ∧
        ⟪v₁, r⟫_ℝ = (n : ℝ) - 2 * (weight c₁ : ℝ) ∧
        ⟪v₂, r⟫_ℝ = (n : ℝ) - 2 * (weight c₂ : ℝ) := by
          refine' ⟨ _, _, _ ⟩ <;> norm_num [ EuclideanSpace.inner_eq_star_dotProduct ];
          · convert inner_product_calculation c₁ c₂ using 1;
          · unfold weight; simp +decide [ dotProduct ] ; ring;
            unfold hamming_distance; simp +decide [ Finset.sum_ite ] ; ring;
            rw [←  show ( Finset.univ.filter fun x => ¬c₁ x = 0 ) = Finset.univ.filter ( fun x => c₁ x = 1 ) from Finset.filter_congr fun x _ => by have := Fin.exists_fin_two.mp ⟨ c₁ x, rfl ⟩ ; aesop ] ; rw [ show ( Finset.univ.filter fun x => ¬c₁ x = 1 ) = Finset.univ \ ( Finset.univ.filter fun x => c₁ x = 1 ) from by ext; aesop ] ; simp +decide [ Finset.card_sdiff, * ] ; ring;
            dsimp [hammingDist]
            rw [ Nat.cast_sub ( le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ) ] ; ring;
            have : Finset.card {x | ¬c₁ x = 0} = Finset.card {x | c₁ x = 1} := by
              apply Finset.card_bijective (fun x => x) (by simp)
              intro i
              constructor
              · intro hi
                simp at *
                push_neg at hi
                refine (ZMod.val_eq_one ?_ (c₁ i)).mp ?_
                simp
                have this : (c₁ i).val < 2 := ZMod.val_lt (c₁ i)
                have : (c₁ i).val ≠ 0 := by exact (ZMod.val_ne_zero (c₁ i)).mpr hi
                grind
              · intro hi; simp at *; grind

            grind
          · unfold weight; norm_num [ dotProduct ] ; ring;
            unfold hamming_distance; norm_num [ Finset.sum_ite ] ; ring;
            rw [ show ( Finset.univ.filter fun x => ¬c₂ x = 1 ) = Finset.univ \ ( Finset.univ.filter fun x => c₂ x = 1 ) by ext; aesop] ; norm_num [ Finset.card_sdiff ] ; ring;
            rw [ Nat.cast_sub ( show Finset.card ( Finset.filter ( fun x => c₂ x = 1 ) Finset.univ ) ≤ n from le_trans ( Finset.card_filter_le _ _ ) ( by norm_num ) ) ] ; ring;
            suffices h₁ : (Finset.card {x | c₂ x = 1} = (hammingDist c₂ zero)) by grind
            dsimp[hammingDist]
            apply Finset.card_bijective (fun x => x) (by simp)
            intro i
            constructor
            · intro hi
              simp at *
              grind
            · intro hi; simp at *;
              refine (ZMod.val_eq_one ?_ (c₂ i)).mp ?_
              simp
              have this : (c₂ i).val < 2 := ZMod.val_lt (c₂ i)
              have : (c₂ i).val ≠ 0 := by exact (ZMod.val_ne_zero (c₂ i)).mpr hi
              grind


      simp_all +decide [ inner_sub_left, inner_sub_right ];
      simp_all +decide [ inner_smul_left, inner_smul_right ];
      simp_all +decide [ mul_div_cancel₀, hn, real_inner_comm ];
      norm_num [ EuclideanSpace.norm_eq, inner_self_eq_norm_sq_to_K ] at *;
      by_cases h : ( n : ℝ ) - ( d : ℝ ) * 2 ≥ 0 <;> simp_all +decide [ Real.sqrt_eq_zero_of_nonpos, mul_assoc, mul_comm, mul_left_comm, div_eq_mul_inv ];
      · field_simp at *;
        -- nlinarith [ show ( weight c₁ : ℝ ) ≤ w by norm_cast, show ( weight c₂ : ℝ ) ≤ w by norm_cast, show ( hammingDist c₁ c₂ : ℝ ) ≥ d by norm_cast, show ( 0 : ℝ ) ≤ Real.sqrt n * Real.sqrt ( n - 2 * d ) by positivity, Real.mul_self_sqrt ( show ( n : ℝ ) ≥ 0 by positivity ), Real.mul_self_sqrt ( show ( n - 2 * d : ℝ ) ≥ 0 by linarith ) ];
        sorry
      · norm_num [ Real.sqrt_eq_zero_of_nonpos ( sub_nonpos.mpr h.le ) ] at *;
        linarith [ show ( d : ℝ ) ≤ hammingDist c₁ c₂ by norm_cast ]

/-
Theorem 7 (Binary Johnson Bound): If w ≤ J2(n, d), then A0(n, d, w) ≤ 2n.
-/
theorem binary_johnson_bound {n d w : ℕ} (h_w : w ≤ n) (h_d : d ≤ n) (h_w_pos : 0 < w) (h_d_pos : 0 < d)
  (h_w_le : w ≤ (n - Real.sqrt (n * (n - 2 * d))) / 2) :
  A0_q_w n d w (ZMod 2) ≤ 2 * n := by
    -- Let $C$ be a code of size $A0(n, d, w)$.
    have h_max_card : ∀ (C : Code n (ZMod 2)), is_distance_at_least C d ∧ is_bounded_weight C w → C.card ≤ 2 * n := by
      intro C hC;
      -- Consider the vectors $u_c = v_c - \alpha r$ where $v_c$ corresponds to codeword $c$, $r$ is the all-ones vector, and $\alpha = \sqrt{n(n-2d)}/n$.
      set v : Codeword n (ZMod 2) → EuclideanSpace ℝ (Fin n) := fun c => fun i => if c i = 1 then -1 else 1
      set r : EuclideanSpace ℝ (Fin n) := fun _ => 1
      set α : ℝ := Real.sqrt (n * (n - 2 * d)) / n
      set u : Codeword n (ZMod 2) → EuclideanSpace ℝ (Fin n) := fun c => v c - α • r;
      -- By `lemma_3_2`, the number of such vectors is at most $2n$.
      have h_lemma_3_2 : ∀ (S : Finset (Codeword n (ZMod 2))), (∀ c ∈ S, u c ≠ 0) → (∀ c1 ∈ S, ∀ c2 ∈ S, c1 ≠ c2 → inner ℝ (u c1) (u c2) ≤ 0) → S.card ≤ 2 * n := by
        intros S hS_nonzero hS_inner
        have h_lemma_3_2 : ∀ (v : Fin S.card → EuclideanSpace ℝ (Fin n)), (∀ i, ‖v i‖ = 1) → (∀ i j, i ≠ j → inner ℝ (v i) (v j) ≤ 0) → S.card ≤ 2 * n := by
          exact fun v a a_1 => lemma_3_2 v a a_1;
        contrapose! h_lemma_3_2;
        obtain ⟨f, hf⟩ : ∃ f : Fin S.card → Codeword n (ZMod 2), Function.Injective f ∧ ∀ i, f i ∈ S := by
          have h_equiv : Nonempty (Fin S.card ≃ S) := by
            exact ⟨ Fintype.equivOfCardEq <| by simp +decide ⟩;
          exact ⟨ _, Subtype.coe_injective.comp h_equiv.some.injective, fun i => h_equiv.some i |>.2 ⟩;
        use fun i => ‖u (f i)‖⁻¹ • u (f i);
        simp_all +decide [ norm_smul, inner_smul_left, inner_smul_right ];
        exact fun i j hij => mul_nonpos_of_nonneg_of_nonpos ( inv_nonneg.2 ( norm_nonneg _ ) ) ( mul_nonpos_of_nonneg_of_nonpos ( inv_nonneg.2 ( norm_nonneg _ ) ) ( hS_inner _ ( hf.2 i ) _ ( hf.2 j ) ( hf.1.ne hij ) ) );
      apply h_lemma_3_2 C;
      · intro c hc; intro H; have := congr_fun H ⟨ 0, Nat.pos_of_ne_zero ( by aesop_cat ) ⟩ ; norm_num at this;
        simp +zetaDelta at *;
        split_ifs at this;
        · linarith [ show 0 ≤ Real.sqrt n * Real.sqrt ( n - 2 * d ) / n by positivity ];
        · rw [ sub_eq_zero, eq_div_iff ] at this <;> norm_num at *;
          · rw [ ← Real.sqrt_mul <| by positivity ] at this;
            rw [ eq_comm, Real.sqrt_eq_iff_mul_self_eq_of_pos ] at this <;> nlinarith [ show ( d : ℝ ) > 0 by positivity, show ( n : ℝ ) ≥ d by norm_cast ];
          · rintro rfl; norm_num at *;
      · intros c1 hc1 c2 hc2 hne;
        apply johnson_bound_inequality h_w h_d h_w_le c1 c2 (hC.left c1 hc1 c2 hc2 hne) (hC.right c1 hc1) (hC.right c2 hc2);
    unfold A0_q_w; aesop;

/-
The vectors u_c in the Johnson bound proof are non-zero if d > 0.
-/
theorem johnson_bound_non_zero {n d : ℕ} (h_d : d ≤ n) (h_d_pos : 0 < d) (c : Codeword n (ZMod 2)) :
  let v : EuclideanSpace ℝ (Fin n) := fun i => if c i = 1 then -1 else 1
  let r : EuclideanSpace ℝ (Fin n) := fun _ => 1
  let α := Real.sqrt (n * (n - 2 * d)) / n
  let u := v - α • r
  u ≠ 0 := by
    cases n <;> cases d <;> simp_all +decide [ Finset.sum_const_zero, sub_eq_iff_eq_add ];
    rw [ funext_iff ] ; norm_num;
    refine' ⟨ ⟨ 0, Nat.succ_pos _ ⟩, _ ⟩ ; split_ifs;
    · exact ne_of_lt ( lt_of_lt_of_le ( by norm_num ) ( div_nonneg ( Real.sqrt_nonneg _ ) ( by positivity ) ) );
    · rw [ eq_div_iff ] <;> try linarith;
      rw [ eq_comm, Real.sqrt_eq_iff_mul_self_eq_of_pos ] <;> nlinarith [ show ( ↑‹ℕ› : ℝ ) ≤ ↑‹ℕ› + 1 by linarith ]

/-
Lemma 3.2: Suppose v_1, ..., v_m are unit vectors in R^n such that <v_i, v_j> ≤ 0 for all i ≠ j. Then m ≤ 2n.
-/
theorem lemma_3_2_new {m n : ℕ}
  (v : Fin m → EuclideanSpace ℝ (Fin n))
  (h_unit : ∀ i, ‖v i‖ = 1)
  (h_dot : ∀ i j, i ≠ j → inner ℝ (v i) (v j) ≤ (0 : ℝ)) :
  m ≤ 2 * n := by
    convert lemma_3_2 v h_unit h_dot using 1

/-
The binary Elias-Bassalygo bound: A(n, d) ≤ (2^n / (n choose w)) * 2n, where w = floor(J2(n, d)).
-/
theorem elias_bassalygo_bound {n d : ℕ} (h_d : d ≤ n) (h_d_pos : 0 < d) :
  let w := Nat.floor (J2 n d)
  (A_q n d (ZMod 2) : ℝ) ≤ (2 ^ n : ℝ) / (Nat.choose n w) * (2 * n) := by
    by_cases hw : Nat.floor ( J2 n d ) = 0 <;> simp_all +decide;
    · -- Since $J2(n, d) < 1$, we have $A_q(n, d) \leq 2^n$.
      have h_bound : (A_q n d (ZMod 2) : ℝ) ≤ 2 ^ n := by
        unfold A_q;
        norm_num [ Finset.max' ];
        intro b hb; norm_cast; exact le_trans ( Finset.card_le_univ _ ) ( by norm_num [ Finset.card_univ ] ) ;
      rcases n with ( _ | _ | n ) <;> norm_num [ Nat.floor_eq_zero.mpr hw ] at *;
      · linarith;
      · grind;
      · exact le_trans h_bound ( le_mul_of_one_le_right ( by positivity ) ( by linarith ) );
    · -- By the Binary Johnson Bound, $A0(n, d, w) \le 2n$.
      have h_johnson : A0_q_w n d (Nat.floor (J2 n d)) (ZMod 2) ≤ 2 * n := by
        apply_rules [ binary_johnson_bound ];
        · unfold J2 at *;
          exact Nat.floor_le_of_le ( by linarith [ show ( Real.sqrt ( n * ( n - 2 * d ) ) : ℝ ) ≥ 0 by positivity ] );
        · exact Nat.floor_pos.mpr hw;
        · exact le_trans ( Nat.floor_le ( by positivity ) ) ( by unfold J2; norm_num );
      -- By Exercise 2, $A(n, d) \le \frac{2^n}{\binom{n}{w}} A(n, d, w)$.
      have h_exercise : (A_q n d (ZMod 2) : ℝ) ≤ (2 ^ n : ℝ) / (Nat.choose n (Nat.floor (J2 n d)) : ℝ) * A_q_w n d (Nat.floor (J2 n d)) (ZMod 2) := by
        convert exercise_2 _ using 1 ; norm_num [ J2 ] at * ; aesop;
        exact Nat.floor_le_of_le ( by linarith [ show ( Real.sqrt n * Real.sqrt ( n - 2 * d ) : ℝ ) ≥ 0 by positivity ] ) ;
      field_simp;
      -- Since $A_q_w n d w \le A0_q_w n d w$, we can substitute this into the inequality.
      have h_subst : (A_q_w n d (Nat.floor (J2 n d)) (ZMod 2) : ℝ) ≤ (A0_q_w n d (Nat.floor (J2 n d)) (ZMod 2) : ℝ) := by
        unfold A_q_w A0_q_w;
        simp +zetaDelta at *;
        rintro y x hx₁ hx₂ rfl; exact Finset.le_max' _ _ ( Finset.mem_image.mpr ⟨ x, Finset.mem_filter.mpr ⟨ Finset.mem_univ _, hx₁, fun c hc => hx₂ c hc ▸ le_rfl ⟩, rfl ⟩ ) ;
      exact h_exercise.trans ( by rw [ div_mul_eq_mul_div ] ; exact div_le_div_of_nonneg_right ( by nlinarith [ pow_pos ( zero_lt_two' ℝ ) n, show ( A0_q_w n d ⌊J2 n d⌋₊ ( ZMod 2 ) : ℝ ) ≤ 2 * n by exact_mod_cast h_johnson ] ) ( Nat.cast_nonneg _ ) )
